version: '3'

services:
  # Nextcloud service
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    depends_on:
      - db
    volumes:
      - ${NEXTCLOUD_DATA_PATH}:/var/www/html
    ports:
      # HTTP Port
      - "80:80"
    environment:
      # Database Access
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}

      # Nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN}
    networks:
      - internal_network
    restart: always

  # Database service
  db:
    image: mariadb
    container_name: nextclouddb
    volumes:
      - ${NEXTCLOUD_DB_PATH}:/var/lib/mysql
    environment:
      - MARIADB_AUTO_UPGRADE=1
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - internal_network
    restart: always

networks:
  internal_network:
    driver: bridge
